import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom'


export default function View(){
  const [instances, setInstances] = useState([]);
  const [userid, setUserid]=useState(undefined)

  const [selectedInstanceId, setSelectedInstanceId] = useState(null);
  const nav=useNavigate()
  const toggleInstanceVisibility = (instanceId) => {
    setSelectedInstanceId(selectedInstanceId === instanceId ? null : instanceId);
  };

  const handleLogout = () => {
    fetch('api/logout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    .then(() => {
      nav('/login'); // Navigate to login page after logout
    })
    .catch(error => console.log(error)); // Handle any errors
  }

    useEffect(()=>{
        fetch('api/info')
        .then(r=>r.json())
        .then(data=>{
            setUserid(data['id'])
        })
    }, [])
    console.log(userid)
    useEffect(() => {
        fetch(`api/instances/${userid}`)
            .then((response)=>response.json())
            .then((data)=>setInstances(data.instances))
    }, [userid]);

    return (
      
      <div
        style={{
          backgroundColor: 'rgba(139, 131, 120, 0.5)',
          display: 'flex',
          alignItems: 'center',
          flexDirection: 'column',
          width: '100vw',
          borderRadius:'20px', 
          position:'relative'
        }}
      >
        <div style={{
          backgroundColor: 'rgba(139, 131, 120, 0.5)',
          display: 'flex',
          alignItems: 'center',
          flexDirection: 'row',
          justifyContent:'space-evenly',
          width: '100vw',
          borderRadius:'20px', 
          position:'relative',
          height:'80px'
        }}>
        <button 
          onClick={()=>nav('/home')} 
          className="flex justify-center rounded-md bg-yellow-600 px-3 py-1.5 text-lg font-regular leading-6 text-white shadow-sm hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600"
          style={{}}
          >Home</button>
        <button
          className="flex justify-center rounded-md bg-yellow-600 px-3 py-1.5 text-lg font-regular leading-6 text-white shadow-sm hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600"
          onClick={handleLogout} 
        >Logout</button>
        <button
          className="flex justify-center rounded-md bg-yellow-600 px-3 py-1.5 text-lg font-regular leading-6 text-white shadow-sm hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600"
          onClick={()=>nav('/sketch')} 
        >Sketch</button>
        <img className="h-14 w-14 rounded-full border" src={`https://phase-5-images.s3.us-west-2.amazonaws.com/download.jpg`} />
        </div>

        <h1 className="mt-10 text-center text-9xl" style={{ color: '#e6bfb3' }}>
          Creations
        </h1>
        <div className="bg-white py-24 sm:py-32">
          <div className="mx-auto grid max-w-7xl gap-x-8 gap-y-20 px-6 lg:px-8 xl:grid-cols-3">
            <div className="max-w-2xl">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">You made some sweet stuff</h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
              Click on a small icon to view the image generated by AI and the sketch you made to generate it.  Hover over the sketch to view details about the parameters you used.
              </p>
            </div>
          </div>
        </div>
        <ul role="list" className="grid gap-x-8 gap-y-12 sm:grid-cols-2 sm:gap-y-16 xl:col-span-2">
        {instances.length > 0 ? (
        instances.map((instance) => (
          <div className='mt-5 text-left' key={instance.id}>
            <div className="flex items-center gap-x-6">
            <img className="h-16 w-16 rounded-full border" src={`https://phase-5-images.s3.us-west-2.amazonaws.com/${instance.images.filename}`} onClick={() => toggleInstanceVisibility(instance.id)} />
            <div>
              <h3 className="text-base font-semibold leading-7 tracking-tight text-gray-900">{instance.id}Text Prompt</h3>
              <p className="text-sm font-semibold leading-6 text-yellow-600">style</p>
            </div>
            </div>
            {selectedInstanceId === instance.id && (
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <img
                  style={{
                    border: '4px solid #343a40',
                    borderRadius: '10px',
                    marginRight: '10px',
                  }}
                  src={`https://phase-5-images.s3.us-west-2.amazonaws.com/${instance.images.filename}`}
                  alt="Instance Image"
                />
                <img
                  style={{
                    border: '4px solid #343a40',
                    borderRadius: '10px',
                    marginRight: '10px',
                  }}
                  src={`https://phase-5-images.s3.us-west-2.amazonaws.com/${instance.sketches.filename}`}
                  alt="Instance Sketch"
                />
              </div>
              
            )}
          </div>
          ))
      ) : (
        <h1>
          Hmm, looks like you have not made anything yet. Care to try?
        </h1>
        )}
        </ul>
      </div>
    )
  }
