"""added userid foreign key to sketches and images

Revision ID: 1b61de2a62a9
Revises: ccf4edae7c13
Create Date: 2023-04-27 09:02:59.008071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b61de2a62a9'
down_revision = 'ccf4edae7c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_images_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sketches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sketches_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('sketches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sketches_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_images_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
