"""updated images table

Revision ID: c53df42c04dd
Revises: 1b61de2a62a9
Create Date: 2023-05-09 11:39:52.906030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53df42c04dd'
down_revision = '1b61de2a62a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('negtext', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('style', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('clip', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cfg', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('cfg')
        batch_op.drop_column('steps')
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('clip')
        batch_op.drop_column('style')
        batch_op.drop_column('negtext')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
