"""added users, sketches, and instances tables

Revision ID: ccf4edae7c13
Revises: 7d02396887fb
Create Date: 2023-04-26 16:47:01.335354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf4edae7c13'
down_revision = '7d02396887fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sketches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('bucket', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('images_id', sa.Integer(), nullable=True),
    sa.Column('sketches_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['images_id'], ['images.id'], name=op.f('fk_instances_images_id_images')),
    sa.ForeignKeyConstraint(['sketches_id'], ['sketches.id'], name=op.f('fk_instances_sketches_id_sketches')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_instances_users_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    op.drop_table('users')
    op.drop_table('sketches')
    # ### end Alembic commands ###
